### ISSUE TITLE
Docker Image does use SQL_USER as Database Name for Startup as well

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [h-mdm/hmdm-docker#10]
Executing 

docker run -d -p 443:8443 -p 31000:31000 -e SQL_HOST=database.host -e SQL_BASE=test -e SQL_USER=hmdm -e SQL_PASS=password -e BASE_DOMAIN=build.h-mdm.com -v /etc/letsencrypt:/etc/letsencrypt -v $(pwd)/volumes/work:/usr/local/tomcat/work --name="hmdm" headwindmdm/hmdm:0.1.0

does try to connect to database hmdm instead of test.

**Comment by GVLLIFESTYLE** [comment]
The issue is here:
# Waiting for the database
until PGPASSWORD=$SQL_PASS psql -h "$SQL_HOST" -U "$SQL_USER" -c '\q'; do
  echo "Waiting for the PostgreSQL database..."
  sleep 5
done

changed to ==>

# Waiting for the database
until PGPASSWORD=$SQL_PASS psql -h "$SQL_HOST" -U "$SQL_USER" -d "$SQL_BASE" -c '\q'; do
  echo "Waiting for the PostgreSQL database..."
  sleep 5
done

solves the issue.
Please fix

**Comment by h-mdm** [comment]
Fixed, thank you for your efforts!

**Comment by GVLLIFESTYLE** [comment]
Will this be rolled out to the official docker repository as well?
