### ISSUE TITLE
support for custom ports

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [h-mdm/hmdm-docker#13]
Even if the ports are mapped to outside like to port 8443 instead of 443, the QR-Code URL in mdm is still on 443.
It would be nice if there would be a variable to define the servers ports especially if port forwarding is in use.

**Comment by GVLLIFESTYLE** [comment]
This leads at the end also to the issue, that the phone cannot connect to the server through the QR-Code

**Comment by h-mdm** [comment]
We presume that standard ports (443 for HTTPS) are used. 

If you need to change the port in the QR code URL, you need to adjust the following:
- Replace 443 to 8443 in the redirection directives in all docker configs
- Replace _PROTOCOL_://_BASE_DOMAIN_ to _PROTOCOL_://_BASE_DOMAIN_:8443 in the templates/conf/context_template.xml
- Rebuild the image from source code to apply changes

**Comment by GVLLIFESTYLE** [comment]
Still it would be awesome to get the port as ENV Variable.Because you can actually chnage the mapping to 8443:8443 at the docker run command, but the aoftware won't work then.
