### ISSUE TITLE
Problem with suggested solution

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [h-mdm/hmdm-docker#14]
Hello!
I configured https://github.com/h-mdm/hmdm-docker/issues/13.
The problem is everything works fine now, but the apks won't download as they seem to be still retriven from 443 instead of the custom port.
Why?

best regards

**Comment by h-mdm** [comment]
Here's how to change APK URLs in the web panel: https://qa.h-mdm.com/17279/

Once you change the base.url parameter in the Tomcat XML config, new uploaded APKs should have correct URLs.
