### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by maciejmackowiak** [h-mdm/hmdm-docker#18]
Are you planning on supporting the ARM architecture?

**Comment by h-mdm** [comment]
All components of Headwind MDM are platform independent, so basically it should work on ARM servers. We accept this as a feature request and in the near future we will check how Headwind MDM works on ARM.

**Comment by maciejmackowiak** [comment]
It seems to work, I've changed this line https://github.com/h-mdm/hmdm-docker/blob/master/Dockerfile#L3C1-L3C2 
to:
`FROM --platform=linux/arm64/v8 tomcat:9-jdk11-temurin-focal`

build the image and it is working.

The tomcat:9-jdk11-temurin-focal image supports more architectures:
![obraz](https://github.com/h-mdm/hmdm-docker/assets/24996403/c1267891-ce72-45e8-9ded-81d314895b7e)

It seems that you don't need any changes just use the `--platform` when building:
https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images

If you like I can help with testing

**Comment by h-mdm** [comment]
Thank you very much for the information!
