### ISSUE TITLE
[FEAT] Allow use of reverse proxies with docker-compose

### ISSUE THREAD

**Issue by pdsccode** [h-mdm/hmdm-docker#19]
Basically, it is not possible to get the software to work when running the docker container from e. g. Portainer and behind a reverse proxy. At least not without rebuilding the whole image.

Please provide a straightforward way to configure the stack to run behind a reverse proxy like most of modern software does.

**Comment by MeenachiSundaram** [comment]
@pdsccode - do you have a steps on how you ran behind the reverse proxy

**Comment by h-mdm** [comment]
The only problem I know when Headwind MDM works behind the reverse proxy is that the Headwind MDM domain name, while being accessed from the Headwind MDM server, should point to the IP address of that reverse proxy, so Headwind MDM can download the launcher APK. For that purpose, set the variable LOCAL_IP to the IP address of the reverse proxy.
