### ISSUE TITLE
Disabling https

### ISSUE THREAD

**Issue by loranger** [h-mdm/hmdm-docker#2]
Hello,

I'd like to test (and use) hmdm on LAN only, using docker, in order to manager/setup/lock/unlock my wms devices.
Is it possible to start the docker without tls keys ?

I use a local non-routable hostname and my docker-server is not open on the web, so certbot cannot validate the http challenge.

Thanks

**Comment by h-mdm** [comment]
To use plain HTTP, I would suggest doing the following:
1. Comment out the "Connector port="8443"..." entry in the tomcat_conf/server.xml
2. Use the parameter -p 80:8080 in the docker run command
This flow hasn't been tested, though. If it won't work, check the Tomcat logs for issues.

**Comment by loranger** [comment]
Thanks for your reply

I did this, rebuild but the service still refuse to launch :

```
hmdm-mdm       | 2022-11-16 10:56:20 (794 KB/s) - ‘LauncherRestarter-1.04.apk’ saved [1653792/1653792]
hmdm-mdm       |
hmdm-mdm       | Looking for SSL keys in /etc/letsencrypt/live/mdm.docker...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
hmdm-mdm       | Keys not found, waiting...
```

**Comment by h-mdm** [comment]
Set HTTPS_LETSENCRYPT to false in the Dockerfile. Or correct the docker-entrypoint.sh and comment out a piece of code blocking the setup.
