### ISSUE TITLE
Use a different base than Ubuntu LTS

### ISSUE THREAD

**Issue by TommyTran732** [h-mdm/hmdm-docker#25]
Ubuntu no longer supports tomcat9, so the container will permanently be stuck on an old release of Ubuntu LTS. Some other distros I have looked at:

- Fedora: the tomcat package is version 9. No nice way to pin the major version though.
- openSUSE: the tomcat package is version 9, and they provide a separate tomcat10 package. It probably will be okay for awhile, though it will be nice to be able to explicitly say tomcat9 because I don't know when tomcat will default to 10.
- Arch: tomcat9 as a package actually exists, so this can easily be pinned.

**Comment by h-mdm** [comment]
Tomcat 9 CAN run on Ubuntu 24.04. The only problem is that Ubuntu 24.04 doesn't have Tomcat 9 in the APT repository. I don't think it would be a big deal for Tomcat supporters to make an Ubuntu 24.04-based image for Tomcat 9, so I hope to see its release soon.

Anyway, Ubuntu is still the most popular Linux distro, so I would rather stay on Ubuntu.
