### ISSUE TITLE
Не проходит авторизация /rest/public/jwt/login

### ISSUE THREAD

**Issue by fenixnow** [h-mdm/hmdm-docker#9]
Всем привет, использую образ `headwindmdm/hmdm:0.1.0` согласно инструкции
Все работает, создал пользователя с полными правами 
![image](https://user-images.githubusercontent.com/13418562/209541654-0ce55c73-48a3-465e-b305-f287990bff8f.png)
пароль 123456

Пытаюсь выполнить метод для получения Токена "/rest/public/jwt/login", выдает ошибку 401. Помогите разобраться

![image](https://user-images.githubusercontent.com/13418562/209541492-742a4692-a9da-45ac-96a5-980dff901fe9.png)

пароль переведен в МД5-хеш согласно инструкции из Свеггера

**Comment by h-mdm** [comment]
Please use capital letters in the password, this should help.

**Comment by fenixnow** [comment]
> Please use capital letters in the password, this should help.

Это решение не помогает. Ошибка сохраняется
